version: "3.3"

services:

  telegraf: # https://hub.docker.com/_/telegraf
    build: telegraf
    image: ${COMPOSE_PROJECT_NAME}_telegraf
    privileged: true
    network_mode: host
    environment:
      HOST_ETC: /host/etc
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_MOUNT_PREFIX: /host
      GOGC: 40
      GOMAXPROCS: 3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:ro
      - /etc:/host/etc:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/utmp:/var/run/utmp:ro
      - telegraf_conf:/etc/telegraf
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

  influxdb: # https://hub.docker.com/_/influxdb
    build: influxdb
    image: ${COMPOSE_PROJECT_NAME}_influxdb
    environment:
      GOGC: 40
      GOMAXPROCS: 3
    ports:
      - 8086:8086
      - 2003:2003
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - influxdb_conf:/etc/influxdb
      - influxdb_data:/var/lib/influxdb
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

  chronograf: # https://hub.docker.com/_/chronograf
    build: chronograf
    image: ${COMPOSE_PROJECT_NAME}_chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
      GOGC: 40
      GOMAXPROCS: 3
    ports:
      - 8888:8888
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - chronograf_data:/var/lib/chronograf
      - chronograf_share:/usr/share/chronograf
    links:
      - influxdb
      - kapacitor
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

  kapacitor: # https://hub.docker.com/_/kapacitor
    build: kapacitor
    image: ${COMPOSE_PROJECT_NAME}_kapacitor
    command: ["wait-for-it.sh", "--timeout=0", "influxdb:8086", "--", "kapacitord"]
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
      GOGC: 40
      GOMAXPROCS: 3
    ports:
      - 9092:9092
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kapacitor_conf:/etc/kapacitor
      - kapacitor_data:/var/lib/kapacitor
    links:
      - influxdb
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

volumes:
  telegraf_conf:
  influxdb_conf:
  influxdb_data:
  chronograf_data:
  chronograf_share:
  kapacitor_conf:
  kapacitor_data:
